const Input = ({ onClick, inputs }) => {
  const {
      
      department,
      teamName,
      locationOfUse,
      monitorManufacturer,
      desktopManufacturer,
      yearOfMonitorManufacture,
      yearOfDesktopManufacture,
      monitorModelName,
      desktopModelName,
      monitorSize,
      monitorCode,
      desktopCode,
      user
  } = inputs;
  return (
    <>
      <input
        type="text"
        placeholder="부서명"
        name="department"
        onChange={onClick}
        value={department}
      />
      <input
        type="text"
        placeholder="팀명"
        name="teamName"
        onChange={onClick}
        value={teamName}
      />
      <input
        type="text"
        placeholder="사용위치"
        name="locationOfUse"
        onChange={onClick}
        value={locationOfUse}
      />
      <input
        type="text"
        placeholder="데스크탑제조사"
        name="desktopManufacturer"
        onChange={onClick}
        value={desktopManufacturer}
      />
      <input
        type="text"
        placeholder="데스크탑모델명"
        name="desktopModelName"
        onChange={onClick}
        value={desktopModelName}
      />
      <input
        type="text"
        placeholder="데스크탑제조년월"
        name="yearOfDesktopManufacture"
        onChange={onClick}
        value={yearOfDesktopManufacture}
      />
      <input
        type="text"
        placeholder="데스크탑코드명"
        name="desktopCode"
        onChange={onClick}
        value={desktopCode}
      />
      <input
        type="text"
        placeholder="모니터제조사"
        name="monitorManufacturer"
        onChange={onClick}
        value={monitorManufacturer}
      />
      <input
        type="text"
        placeholder="모니터모델명"
        name="monitorModelName"
        onChange={onClick}
        value={monitorModelName}
      />
      <input
        type="text"
        placeholder="모니터제조년월"
        name="yearOfMonitorManufacture"
        onChange={onClick}
        value={yearOfMonitorManufacture}
      />
      <input
        type="text"
        placeholder="모니터코드명"
        name="monitorCode"
        onChange={onClick}
        value={monitorCode}
      />
      <input
        type="text"
        placeholder="모니터사이즈"
        name="monitorSize"
        onChange={onClick}
        value={monitorSize}
      />
      <input
        type="text"
        placeholder="사용자명"
        name="user"
        onChange={onClick}
        value={user}
      />
    </>
  );
};

export default Input;
